name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build Process for Heroku Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tranquil-river-00045" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}